[package]
name = "waow"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.0"
pixels = "0.13.0"
env_logger = "0.11.2"
error-iter = "0.4"
log = "0.4"
winit_input_helper = "0.14"
