[package]
name = "waow"
version = "0.10.0"
edition = "2021"
description = "A begginer friendly creative coding library"
license = "MIT OR Apache-2.0"

[dependencies]
winit = "0.28.0"
pixels = "0.13.0"
env_logger = "0.11.2"
error-iter = "0.4"
log = "0.4"
winit_input_helper = "0.14"
